// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Minus-1]
	_ = x[Star-2]
	_ = x[FSlash-3]
	_ = x[LParen-4]
	_ = x[RParen-5]
	_ = x[Equal-6]
	_ = x[Newline-7]
	_ = x[Ident-8]
	_ = x[Number-9]
	_ = x[EOF-10]
}

const _TokenType_name = "PlusMinusStarFSlashLParenRParenEqualNewlineIdentNumberEOF"

var _TokenType_index = [...]uint8{0, 4, 9, 13, 19, 25, 31, 36, 43, 48, 54, 57}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
